### PR TITLE
Added possibility to install submodules of a git repository or local repository

### PR DESCRIPTION
**Pull request by Thellior**
<h1>Intentions</h1>
Some organisations are using a mono repository structure. They want to install shards based on a submodule of a git repository. Rails / Angular are examples of frameworks that are using the mono repo style. Because this was not supported in shards yet i adjusted the code to be able to install submodules.

<h1>What is done</h1>

- Changed the git resolver to check for the "dep" keyword in the dependencies. If there is a a dep defined it will add it to the refs of the git commands so the correct submodule is installed. If there is no dep defined it will use the normal flow that was already there.
- Changed the factory support test file to have seperate functions so we can reuse them in the new mono repo factory methods.
- Add the mono repo factory method. The factory method will initialise a mono repo with submodules. 
- Added integrations tests to verify that the submodules are installed with git and path.

<h1>Instructions</h1>

In the shards.yml you can now specify a extra attribute called "dep". The dep will describe the path to the submodule inside the git repository.

```yml
dependencies:
  logger:
    git: git@github.com:ultimategogetter/test.git
    dep: libs/logger
```

<h1>TODO</h1>

- When the change is accepted write documentation how to use this new feature

### CODE REVIEW

**Comment by ysbaddaden** [comment]
Sorry, but I think enforcing 1 repository = 1 shard isn't much to ask, and is a better idea overall. If many repositories aren't possible for some reason, individual modules can be under `src` and be included with an explicit `require "foo/bar"`.

**Comment by Thellior** [comment]
@ysbaddaden I understand that in some use cases the 1 repository = 1 shard is good option. For some companies or frameworks the mono repo with multiple shards is a better option for them. I think providing both options as a shards manager is a nice addition to the stack. What is holding you back from allowing both solutions?

**Comment by ysbaddaden** [comment]
1. Increased complexity: dealing with branches and refs is hellish enough and the source of many bugs; I don't want to deal with shards in subfolders in addition to that.
2. No real benefit of having sub-shards: we still clone the whole repository (where rails/angular generate smaller packages).
3. I really don't like this design.

I prefer monolithic applications, but I believe libraries should be either fat (allowing explicit requires of sub-modules) or developed in their own repository if they're supposed to be autonomous.

**Comment by eliasjpr** [comment]
This is a nice feature contribution for `shards`, for an organization or open source project be able to use a Monorepo style to host their shards. There some real benefits of Monorepos, this might shed some light https://www.google.com/search?source=hp&ei=f36_W5imFaaMggfTmoCwBQ&q=monorepo+advantages&btnK=Google+Search&oq=monorepo+advantages&gs_l=psy-ab.3..0.1179.7531..7693...1.0..0.95.1488.27......0....1..gws-wiz.....0..0i131j0i10j0i22i30.tiUBGOKeJoE 

I think there are some valid use cases that outweighs any personal preferences, if thats fair to say. I do not see the added complexity to this project `Shards` in 6 file change. 

If an org wants to have the complexities that comes with Monorepos I think that should be their choice, the good part is that there can be support within the official crystal tool `shards`, a tool that aims to simplify development workflow within crystal ecosystem.

**Comment by straight-shoota** [comment]
I'm not sure  follow the intentions of this change completely.

Shards is based on single repository distribution. And I think that's a good thing. Changes like this introduce a lot of complexity to the application. It's "changes in 6 files" (whatever that metric is supposed to mean) and these changes need to be supported in future versions and integrated with future feature enhancements. It adds a burden on the continuing development of this software.

And frankly, I see hardly any benefit from it.

People are welcome to develop in a monorepo. Or whatever development strategy they favour. You can develop it anyway you want. You don't even need to use any SCM system for development, if you don't feel like.

But Shards is not about *development*: It's about *distribution*.

And the distribution format (currently) supported by Shards uses a Git repository for each shard. That's a relatively simple rule (but it already comes with great complexity to handle correctly).
All you have to do to distribute a shard for using it with Shards is to put it in a git repository. If you already develop it in a single git repository, you can just use that, and it's ready to go. Otherwise you'll just have to setup a Git repository as distribution channel.  This step is similar to publishing a library with any centralized dependency register like rubygems, npm etc. With shards you can be the registry yourself (or you trust any Git provider with that), you simply have to follow the distribution format: a single git repository with a `shard.yml` file.

**Comment by straight-shoota** [comment]
That being said, I suppose more or less the same as this PR could already be accomplished with a configuration like this:

```yaml
dependencies:
  monorepo:
    git: git@github.com:ultimategogetter/test.git
  logger:
    path: lib/monorepo/libs/logger
```

I haven't tested it and it might not work right out of the box, but it shouldn't be very difficult to make this work. I'm not sure it's worth it considering my previous comment, but it might be a useful workaround at least during development. But you could also just put the monorepo in any other location manually and just link to its libraries with `path:`.

**Comment by ysbaddaden** [comment]
If someone wants monorepo I let *them* deal with the complexity. *I* won't deal with the complexity. Sorry.

I don't want to deal with bugs such as "shards is using wrong shard.yml from monorepo subfolder" or conflict issues because they all point to the same git url, but are actually different dependencies, or worse : "I want to install different versions of shards under monorepo"...

Testing the happy path isnt enough, I'm afraid most integration tests should be duplicated to test that they do work with monorepos. Implementing new features would mean to take care that they do work with monorepos, and so on :-(

I'm closing. I don't want to give the impression that we'll support monorepos.

Maybe `path` could be fixed to accept relative paths, but one can just create symlinks manually under `lib` and commit them, so I'm not even sure.

**Comment by RX14** [comment]
Also, since we base versions off git tags, and git tags are global to a whole repo, every shard sharing a repo would need to have the same version which is impractical. I don't see how this could be reasonably implemented.

**Comment by eliasjpr** [comment]
Versioning is something that the Monorepo try to address. 

I understand if this is something that Shards and Community does not want to support.

**Comment by eliasjpr** [comment]
@ysbaddaden you could have left this PR open or move it to a thread, maybe it would've lead to a solution that is simply, efficient and make everyone happy. Closing it just shuts down any possibility and gives an impression that people thoughts and arguments are not enough to persuade the maintainers of this open source project. We do not have to agree but a least allow for the conversation flourish so we can arrive to a conclusion.

**Comment by jwoertink** [comment]
I know this is an old issue, but wanted to bring this up again as I just ran in to this. I have a repo that contains more than just crystal. I put my shard in to a subfolder of the repo, but I can't link to it without getting this error since the `shard.yml` isn't at the top level of the repo.

> Failed git ls-tree -r --full-tree --name-only refs/tags/v0.1.0 -- shard.yml (). Maybe a commit, branch or file doesn't exist?

When if the key just specified where the location of the shard.yml was? Maybe something like:

```yml
dependencies:
  thing:
    github: jwoertink/thing
    branch: master
    require: subdirectory/
```

Where the shard.yml is located in a folder called "subdirectory". Then in this case, we could have a single repo that contains multiple shards by doing something like

```yml
dependencies:
  orm:
    github: jwoertink/monorepo
    branch: master
    require: orm/
  logger:
    github: jwoertink/monorepo
    branch: master
    require: logger/
```

Where the structure is like:

```
orm/
  src/
    orm.cr
  shard.yml
logger/
  src/
    logger.cr
  shard.yml
README.md
```

Obviously the key name `require` could be whatever, but I think this wouldn't be a major change, and would support the ideas of this PR.

**Pull request closed without merging**
