### PR TITLE
Fix issues highlighted by Ameba linter

### PR DESCRIPTION
**Pull request by Sija**
SSIA

### CODE REVIEW

**Comment by ysbaddaden** [comment]
There is no benefit to proposed changes. the `&` forms are uglier, and prefixing unused variables with `_` isn't even a thing in Crystal.

**Comment by Sija** [comment]
> There is no benefit to proposed changes.

Cleaner code is the benefit, that's what, among other things, linting does.

> the `&` forms are uglier

Perhaps, I could revert that If you'd wait...

> prefixing unused variables with `_` isn't even a thing in Crystal.

_a thing_? that's used convention signifying unused variables in similar vein to `_` - which **is a thing** in Crystal...

**Comment by RX14** [comment]
1. Ameba is just a few people's opinion of what's cleaner code
2. Automated linters are notably bad at using discretion because they apply simplistic rules, and code style definitely requires context to do correctly.
3. Open source maintainers are busy, any style PR is automatically going to be put at the bottom of the review queue anyway. Often it's just best to close the PR early to save everyone's time because you know you're never going to review or merge these PRs.

This applies to crystal-lang/crystal too, please don't send linter PRs, PRs converting strings to chars, or any other kind of lazy PR. I personally will refuse to review or merge one, the rest of the core team can waste their time as they wish.

**Comment by ysbaddaden** [comment]
This patch was purely opinion-based, and my opinion differs (strongly):

- `_var` has a lang meaning in Erlang, not in Crystal;
- I like the `&.` call form, except for operators where they hinder readability;
- a few lost `ex =` in specs doesn't hurt.

**Pull request closed without merging**
