### PR TITLE
Honour `CRYSTAL` env var

### LINKED ISSUE #406: Resolution of crystal dependency is hard tied to `crystal` executable
The implicit crystal dependency introduced in #395 calls `crystal env` to determine the crystal version it should treat as a dependency.
It assumes you're installing dependencies for use with `crystal` binary in current PATH. But that might not at all be what I intend to do.
If I want to build with a compiler that's not `crystal`, `shards` might install wrong dependency versions when it implicitly uses `crystal` as reference. For example, I usually have a couple different compiler executables in my PATH. Currently, the versions are not very different, so it's probably not going to cause many problems. But as soon as we move on after 1.0, it would be quite common to have different compiler versions available, say `crystal-1.0` and `crystal-1.1` to test against the different releases.
Using `--ignore-crystal-version` would completely disable the crystal dependency and thus doesn't reproduce the same behaviour as when using a proper version.

Currently, you would have to change `PATH` to point to the appropriate executable in order for shards to pick the correct version as dependency. That requires much effort and can easily cause issues by itself. We need a better solution.

Ideas that come to mind are to specify either the crystal version directly or the path to the compiler that should be used as configuration option to shards.
A very neat solution would use the `CRYSTAL` enviornment value. That's typically used to make the compiler executable configurable in Makefiles. So it would integrate very well with that.

### PR DESCRIPTION
**Pull request by straight-shoota**
This is a reissue of #415 reduced to the original scope. It makes `shards` honour the `CRYSTAL` environment variable when calling the `crystal` program to determine the Crystal version and for `shards build`.

Resolves #406

### CODE REVIEW

**Comment by oprypin** [comment]
Specs fail on Windows

**Comment by straight-shoota** [comment]
Yeah, that was #532

**Comment by oprypin** [comment]
Seems not ¯\\\_(ツ)_/¯

**Comment by oprypin** [comment]
Seems not ¯\\\_(ツ)_/¯

**Comment by straight-shoota** [comment]
Yeah, now we get the actual failures on windows. Not the unrelated ones.

**Comment by Sija** [comment]
Windows doesn't like `${CRYSTAL:-crystal}` within the command.

**Review by oprypin — APPROVED** [review]

**Pull request merged**
