### PR TITLE
Be more specific about uniqueness of crystal shard names.

### PR DESCRIPTION
**Pull request by tomas**

### CODE REVIEW

**Comment by ysbaddaden** [comment]
As stated in https://github.com/crystal-lang/shards/issues/137#issuecomment-262414743 a shard name must still be unique, whatever the context.

**Comment by vegai** [comment]
Should this be closed if it won't be merged?

**Comment by tomas** [comment]
@RX14 @vegai Why not?

**Comment by RX14** [comment]
Because the statement is incorrect. Your package name SHOULD be globally unique.

**Comment by tomas** [comment]
Even though that's pretty much impossible without a central registry, it still wouldn't hurt to state *that* in the SPEC.md file, would it? 

Anyway, thanks for at least considering this. It would have been nice if you had explained the reason why the PR wasn't merged though... (without me having to ask for it).

**Comment by RX14** [comment]
@tomas, I think @ysbaddaden was perfectly clear:

>a shard name must still be unique, whatever the context

**Comment by tomas** [comment]
But you're missing the part where he says that 

> shards' names are thus unique in the context of a shard.yml.

That's why I'm saying that it wouldn't hurt to be extra clear about this. That's all.

**Comment by ysbaddaden** [comment]
Your phrasing would bring ambiguity when there is none: a ahead name is unique, period.

SPEC details rules for the `shard.yml` file, and it doesn't care about implementation choices (no central registry). We could eventually decide to have one, or to have an alternative implementation with a central registry, still compatible with SPEC.

**Pull request closed without merging**
