### PR TITLE
Add continuous testing (including Windows) using GitHub Actions

### PR DESCRIPTION
**Pull request by oprypin**

### CODE REVIEW

**Comment by oprypin** [comment]
Sample: https://github.com/oprypin/shards/actions/runs/362672977

**Review by straight-shoota — APPROVED** [review]

**Comment by oprypin** [comment]
Sample: https://github.com/oprypin/shards/runs/1511470718

**Review by straight-shoota — APPROVED** [review]

**Comment by oprypin** [comment]
How is it that pull requests, each of which might break Windows specs, are being merged before this???

**Comment by oprypin** [comment]
Thankfully it still passes
https://github.com/oprypin/shards/runs/1546845465

**Comment by straight-shoota** [comment]
We're still missing a second approval 😏 But I'll merge anyway. It should be fine.

**Pull request merged**
