### PR TITLE
Fix build and test process

### PR DESCRIPTION
**Pull request by conradwt**
This PR fixes the build and test process for macOS.

## Enhancements

- Fix:  macOS `install` command doesn't have a `-t` option

- added `make` rule to install dependent shards

### macOS 10.14 Status

- [x] installed successfully

- [x] tests ran successfully

### Ubuntu 18.04 Status

- [x] installed successfully

- [x] tests ran successfully

### CODE REVIEW

**Comment by ysbaddaden** [comment]
I misread. Running `bin/shards install` manully once ain't much of an hassle to be capable to run tests, but it's a pain when developing to have it run each time, because it will try to update the remote git repository on each test run.

**Comment by conradwt** [comment]
@ysbaddaden Should I mark the `CHANGELOG` as follows:

```
## v0.8.2 (UNRELEASED)
```

**Comment by conradwt** [comment]
@ysbaddaden I'm in the process of building a Portfile  for `shards`.  Now, Travis CI is failing because 
minitest isn't installed.  How should I proceed with getting this PR published?

**Comment by conradwt** [comment]
@ysbaddaden Please let me know if there's anything else I need to do with this PR because I need to get this one published to complete work on the `Amber` MacPorts Portfile.

**Comment by ysbaddaden** [comment]
Merged as 1d249fbf1a7bb0995667b792f5b42190127ba441.

**Pull request closed without merging**
