### PR TITLE
[WIP] Run tests on GitHub Actions

### PR DESCRIPTION
**Pull request by waj**
Not to merge yet. I'm testing GitHub Actions.

### CODE REVIEW

**Comment by waj** [comment]
Ouch! I thought it would run the tests on Actions without merging. But, pfff... it makes sense it doesn't.

**Comment by straight-shoota** [comment]
@oprypin did this for crystal win32, I'm sure there's a way. Should work in a private fork.

**Comment by waj** [comment]
Sure! It’s working on my fork. I’ll push it to this repo once it’s ready an PR from here.

**Comment by Sija** [comment]
Superseded by #448

**Pull request closed without merging**
