### PR TITLE
Fix README typo, and clarify

### PR DESCRIPTION
**Pull request by lukeholder**

### CODE REVIEW

**Comment by straight-shoota** [comment]
While you're at it, could you replace `crystal deps` with `shards`? `crystal deps` just calls `shards` and the shards exectuable should better be used independetly from the compiler.

/cc @ysbaddaden

**Comment by RX14** [comment]
@straight-shoota please submit that change as a separate PR.

**Comment by straight-shoota** [comment]
Sure, but it will need a rebase after this is merged (or vice versa). That's why I suggested to include it here for simplicity.
I wouldn't consider it anything else than a clean-up to keep up with the other mentions of which-command-to-be-used in this file so I think this would also fit in here nicely.

**Comment by RX14** [comment]
This wasn't fixed. The typo is still in the readme.

**Pull request closed without merging**
