### PR TITLE
Use git's `checkout` feature directly to write out repo files

### PR DESCRIPTION
**Pull request by oprypin**
to avoid relying on a shell to pipe into `tar`.

Caveat: `git checkout` also updates the index in the repository, but that shouldn't be a problem here (is there even any index in a bare repo to start with?)

This is part of work to bring 'shards' to Windows.

### CODE REVIEW

**Review by jhass — APPROVED** [review]

**Review by straight-shoota — APPROVED** [review]

**Comment by oprypin** [comment]
What's the holdup with this particular pull request (the last one)? 😅

**Comment by straight-shoota** [comment]
I was waiting for CI to finish after I fixed the merge conflict. Not sure why the milestone was changed. It should be ready to merge right away.
@bcardiff Anything holding this up?

**Comment by bcardiff** [comment]
I changed the milestone because v0.12.0 is released already, but the milestone was not closed. I created a vNext because I'm not sure the next is 0.12.1 or 0.13.0

**Comment by straight-shoota** [comment]
Thanks @oprypin

**Pull request merged**
