### PR TITLE
Bump supported Crystal version to ">= 0.35.0" in shard.yml

### PR DESCRIPTION
**Pull request by Sija**

### CODE REVIEW

**Review by straight-shoota — APPROVED** [review]

**Comment by bcardiff** [comment]
I don't agree with >= version restrictions. Compile with --ignore-crystal-version until 1.0 is out and ecosystem is updated.

**Comment by straight-shoota** [comment]
But it *is* compatible with 0.35.0 and 1.0. If not open ended, it could at least be something like `crystal: >= 0.35.1, < 2.0`.

I am strictly against forcing to use `--ignore-crystal-version` everywhere as per https://github.com/crystal-lang/shards/issues/413#issuecomment-727633776. It that's supposed to be the solution, it would be much, much better for everyone to just not enforce Crystal versions at all.

**Comment by Sija** [comment]
@bcardiff As far as I understand, shards _are_ and **will be** compatible with crystal `>= 0.35.0`, right?  _I don't agree with_ doesn't sound like an argument but your private opinion, no offence - and it seems a bit far away from welcoming community standards and meritocratic approach, which I hope you agree with as beneficiary.

**Comment by bcardiff** [comment]
@Sija I believe I have expressed my concerns in posts and issues already why not having and upper limit in the stated crystal version is a practice I won't encourage.

@straight-shoota proposal is better in this regard. Yet we need first to release 1.0-pre1 and to everybody to honor that no more breacking changes are wanted in 1.x to make the statement of for `< 2.0`. Even small breaking changes that are motivated by valid cleanups and improvements will break that statement.

Of course, there are ways of disregard whatever version restriction is stated. You need to put whatever you want in lib and the compiler lookup path will use it. But I prefer for version restrictions to mean something, even if they are more conservative.

**Comment by straight-shoota** [comment]
I don't think you have expressed your concerns enough. At least I don't follow them. And there was no response to the latest counter arguments in #413.

Around major releases with breaking changes, a version restriction is always suject to being incorrect, wether it's overspecific or underspecific. Being conservative IMO has mostly ideal value, but practically it's relatively irrelevant whether the stated version compatibility is factual. We're only talking about a development version here. It just makes using it harder for everyone. I don't think we need to release 1.0-pre1 before stating that shards is compatible with 1.0. At this point it should be a given that the next shards release is *definitely* compatible with 1.0.

**Pull request closed without merging**
