### PR TITLE
Update Crystal version in shard.yml

### PR DESCRIPTION
**Pull request by Sija**
Since Crystal 0.24 is around the corner 🎉

### CODE REVIEW

**Comment by ysbaddaden** [comment]
We can't refer to a crystal version that doesn't exist. I use 0.24 in commit messages because this is very likely the number that will be used. I have no idea when it will be released.

**Comment by ysbaddaden** [comment]
Done in 95c6a61129accc6a0ab057595f73858d2b0fa38e

**Comment by RX14** [comment]
0.24 still isn't released... It's got a preliminary tag but given the bugs that https://github.com/crystal-lang/crystal/pull/5114 introduced, I cannot believe that this release wil not be re-tagged.

**Comment by mverzilli** [comment]
Both crystal-lang/crystal#5175 and crystal-lang/crystal#5177 already have PRs waiting to be merged. @RX14 is there any other pending bug? I guess we can re-tag if there isn't.

**Comment by ysbaddaden** [comment]
I'm just preparing for Crystal 0.24.0, as requested by @matiasgarciaisaia. Also:
- master already fails to compile with 0.23.1;
- bugs from https://github.com/crystal-lang/crystal/pull/5114 don't affect Shards.

**Comment by RX14** [comment]
@mverzilli i think those 2 PRs are it, but my point was that they weren't merged so we'll have to retag at least.

**Pull request closed without merging**
