### PR TITLE
Use read_file macro instead using OS-dependent `cat`

### PR DESCRIPTION
**Pull request by Sija**
SSIA

### CODE REVIEW

**Comment by ysbaddaden** [comment]
Looks good. Yet, CI is red. Maybe master got broken, but I'd like CI to be green before merging PR.

**Comment by Sija** [comment]
Sure, that's understandable, yet AFAICS it's an unrelated fail - it fails because due to changes related to displaying error messages.

**Comment by ysbaddaden** [comment]
Would you be so kind to provie a PR to fix it? That would highly appreciated!

**Comment by Sija** [comment]
@ysbaddaden Sure, np. Btw, seems like `--no-color` switch ain't working.

**Comment by ysbaddaden** [comment]
No colors only affects shards (logs have no colors) not the crystal build command (errors now always have colors, despite not being a tty).

**Comment by ysbaddaden** [comment]
The cat call breaks at compile time if the VERSION file is missing. What happens with read_file macro?

**Comment by straight-shoota** [comment]
`read_file` fails as well.

**Comment by ysbaddaden** [comment]
Thank you!

**Pull request merged**
