### PR TITLE
Add macOS nightlies to CI

### PR DESCRIPTION
**Pull request by Sija**
Refactored some parts as well like `include`-ing windows in the `matrix` instead of having it there from start - especially apt as windows support is still in-the-works.

### CODE REVIEW

**Review by straight-shoota — APPROVED** [review]

**Comment by Sija** [comment]
This could be merged...

**Comment by Sija** [comment]
@bcardiff Could you please review this?

**Comment by bcardiff** [comment]
Is there a reason to exclude windows from using crystal latest?

**Comment by Sija** [comment]
@bcardiff yes, it doesn't work. for more detailed explanation please ask @oprypin.

**Comment by oprypin** [comment]
And the reason for that is https://github.com/crystal-lang/distribution-scripts/issues/64#issuecomment-778775239

**Comment by oprypin** [comment]
@Sija Why do you have to change the whole file's formatting to adhere to your liking?

**Comment by Sija** [comment]
@oprypin _Whole file_? Don't exaggerate, adding some spaces for readability and changing name of one job is not _whole file_. What's wrong with those changes anyway?

**Comment by asterite** [comment]
@Sija They are irrelevant to the change you want to make.

If you want to change someone else's style, I think that should be discussed and done separately.

Code is written by people if you go and change that when it's not needed, while also adding additional changes, the ones that wrote the original code might think "What's your problem with my style? BAM. I don't like your PR."

Not that that will effectively happened. But at least in my case when I contribute to a project I tend to avoid changing style things if they have nothing to do with the PR's goal.

**Comment by asterite** [comment]
They also make reviewing the PR harder! "Why was this changed? Is this relevant? I don't understand."

**Review by bcardiff — APPROVED** [review]
I'm fine the changes. Let's keep it calm. But I agree that changes that satisfies author's taste should be avoided in general.

**Pull request merged**
